const { VITE_KEYCLOACK_URL, VITE_KEYCLOACK_REALM, VITE_KEYCLOACK_CLIENT_ID } =
  import.meta.env;

export const KEYCLOACK_AUTH_URL = VITE_KEYCLOACK_URL;
export const KEYCLOACK_REALM = VITE_KEYCLOACK_REALM;
export const KEYCLOACK_CLIENTID = VITE_KEYCLOACK_CLIENT_ID;
